# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='alt_address1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='alt_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='alt_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
