# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181210_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='alt_address1',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='alt_address2',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='alt_city',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='alt_postal_code',
        ),
    ]
