# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181210_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='country',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='userdata',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
