# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-23 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_item_price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
