# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-26 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderitem_total_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_item_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
