# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('setnumber', models.DecimalField(decimal_places=0, max_digits=8)),
                ('short_description', models.CharField(default='', max_length=254)),
                ('long_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image1', models.ImageField(upload_to='img')),
                ('image2', models.ImageField(upload_to='img')),
                ('main_category', models.CharField(default='', max_length=100)),
                ('sub_category', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
