# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='long_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='item_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
