# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181210_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
