# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
