# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181227_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
