# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-26 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='useful',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='views',
        ),
    ]
