# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190126_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_id',
        ),
    ]
